<?php
/**
 * Created by PhpStorm.
 * User: dyangalih
 * Date: 04/11/18
 * Time: 04.06
 */

namespace WebAppId\Content\Tests\Unit\Repositories;


use WebAppId\Content\Repositories\CategoryStatusRepository;
use WebAppId\Content\Tests\TestCase;

class CategoryStatusTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function getDummy()
    {
        $objCategoryStatus = new \StdClass;
        $objCategoryStatus->name = $this->getFaker()->name;
        return $objCategoryStatus;
    }
    
    public function createDummy()
    {
        return $this->getContainer()->call([$this->inject(), 'addCategoryStatus'], ['request' => $this->getDummy()]);
    }
    
    private function inject(){
        return $this->getContainer()->make(CategoryStatusRepository::class);
    }
    
    public function testAddCategoryStatus()
    {
        $result = $this->createDummy();
        if ($result == null) {
            $this->assertTrue(false);
        } else {
            $this->assertTrue(true);
        }
    }
    
}