<?php
/**
 * Created by PhpStorm.
 * User: dyangalih
 * Date: 06/11/18
 * Time: 06.56
 */

namespace WebAppId\Content\Tests\Feature\Services;


use WebAppId\Content\Services\ContentService;
use WebAppId\Content\Tests\TestCase;
use WebAppId\Content\Tests\Unit\Repositories\ContentTest;

class ContentServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function contentService()
    {
        return $this->getContainer()->make(ContentService::class);
    }
    
    public function contentRepositoryTest()
    {
        $contentRepositoryTest = $this->getContainer()->make(ContentTest::class);
        $contentRepositoryTest->setUp();
        return $contentRepositoryTest;
    }
    
    public function testUpdateContentStatus(){
        $result = $this->contentRepositoryTest()->testAddContent();
        $status_id = $this->getFaker()->numberBetween(1,4);
        $resultUpdateStatus = $this->getContainer()->call([$this->contentService(), 'updateContentStatusByCode'],['code' => $result->code, 'status' => $status_id]);
        
        if($resultUpdateStatus == null){
            self::assertTrue(false);
        }else{
            self::assertTrue(true);
            self::assertEquals($status_id, $resultUpdateStatus->status_id);
        }
    }
}